### PR TITLE
update item model to include s3 storage and bucket

### PR DESCRIPTION
**Pull request by xiranou**
as far as my local version goes, everything works fine. the problem was with paperclip in the item model, need to add s3 storage and bucket name. i pulled the env vars from heroku and everything looks fine locally.

### CODE REVIEW

**Comment by vnikiten01** [comment]
am I looking in the wrong place.  I dont see the env vars on heroku.  Did
you guys start a different heroku than the one we had originally?
AWS_BUCKET
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
S3_BUCKET_NAME

**Comment by xiranou** [comment]
yea, it's on a different heroku. easier to test when we have a spare

**Comment by vnikiten01** [comment]
I take it ed has to add me as a collaborator in order for me to see it.

**Comment by xiranou** [comment]
yea, email him

**Comment by Edchen001** [comment]
I added you as a collaborator. let me know if you have trouble accessing it.

**Comment by vnikiten01** [comment]
all good thanks ed

**Pull request closed without merging**
